<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon />
    <AssemblyName>WinWidget</AssemblyName>
    <RootNamespace>WinWidget</RootNamespace>
    <SupportedOSPlatformVersion>10.0.22000.0</SupportedOSPlatformVersion>
  </PropertyGroup>
</Project>

